import Header from 'next/head';
import About from '@/components/About/About';
import Contact from '@/components/Contact/Contact';
import Footer from '@/components/Footer/Footer';
import Navbar from '@/components/Navbar/Navbar';
import styles from '../../styles/about.module.scss';

const index = () => (
    <div className={styles.about}>
        <Header>
            <title>About</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Header>
    <div className={styles.about_page}>
        <Navbar />
        <About pt="70px" social={true} />
        <Contact />
        <Footer />
    </div>
    </div>
);

export default index;