import Header from 'next/head';
import About from '@/components/About/About';
import Contact from '@/components/Contact/Contact';
import Footer from '@/components/Footer/Footer';
import Navbar from '@/components/Navbar/Navbar';
import styles from '../../styles/about.module.scss';

const index = ({social}) => (
    <div className={styles.about}>
        <Header>
            <title>About</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Header>
    <div className={styles.about_page}>
        <Navbar />
        <About pt="70px" social={true} />
        {/* <Head title="Skills"/>
         <div className={style.about_main}>
       <Image
          src={profilPic}
          className={style.profileImg}
          alt="Software Engineer"
          height={400}
          width={400}
          layout="responsive"
        />
        <div className={style.text}>
          <h2>Hi, I&apos;m Agasef</h2>
          <p>
            Hi. I&apos;m 20 and currently student. I&apos;m open to new innovations and
            love learning new technologies. Highly motivated Front End Developer
            with experience in HTML/CSS,JavaScript, React. Adept at contributing
            to a highly collaborative work environment, finding solutions, and
            determining customer satisfaction.
          </p>
          <p className={style.skill}>Among my areas of expertise are:</p>
          <ul>
            <li>Javascript/TypeScript</li>
            <li>React Js/Redux</li>
            <li>Next.js</li>
            <li>Node.js/Express.js</li>
            <li>HTML</li>
            <li>CSS/SCSS/SASS</li>
            <li>Material Design/Ant Design</li>
            <li>TailwindCss</li>
            <li>Styled-Components</li>
            <li>Core Java/Sql</li>
            <li>Bootstrap</li>
            <li>Git/GitHub</li>
            <li>Experience with Figma</li>
          </ul>
          {social && (
            <div style={{ paddingTop: "5px" }}>
              <p>Socials: </p>
              <SocialIcon />
            </div>
          )}
        </div> 
      </div> */}
        <Contact />
        <Footer />
    </div>
    </div>
);

export default index;