import React from "react";
import styles from "./loading.module.css";
import { Bars } from "react-loading-icons";
import Header from 'next/head';

export const Loading = () => {
  return (
    <div className={styles.container}>
      .
      <Header>
            <title>Loading....</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Header>
      <Bars className={styles.bars} fill="green" speed={0.75} height={100} />
    </div>
  );
};
