import Head from "next/head";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import About from "@/components/About/About";
import Header from "@/components/Header/Header";
import Projects from "@/components/Projects/Projects";
import Contact from "@/components/Contact/Contact";
export default function Home({ projects }) {
  return (
    <div className="container">
      <Head>
        <title>Portfolio | Agasef</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Navbar />
        <Header />
        <About />
        <Projects projects={projects} />
        <Contact/>
        <Footer />
      </main>
    </div>
  );
}
export async function getStaticProps() {
  const res = {
    message: [
      {
        _id: "1",
        title: "JobMaster -Job circular app",
        detail:
          "JobMaster is a job circular web application. It's only for the frontend design with fully responsive. People can find jobs from here by category and can hire a person for their personal and business needed. People can apply for a job. There is also a blog posts section. Users can get an idea of what other users got hired and their job experience by reading this article. People can hire a person on this website by visiting their profile. In the candidate profile, you can see their work experience and their skills. There is the process how to hire the candidate.",
        images: [
         "https://res.cloudinary.com/dfou0tzco/image/upload/v1675411227/jobmaster_srckz5.jpg"
        ],
        features: [
          "Fully responsive webpages.",
          "Filter and Search functionality",
        ],
        tools: ["Javascript","NextJS", "ReactJS", "SASS", "CSS3"],
        liveLink: "https://jobmasternext.vercel.app/",
        githubLink: "https://github.com/agasefamircan/jobmaster",
        left: true,
        __v: 0,
      },
      {
        _id: "2",
        title: "Weblog",
        detail:
          "Meta UI is a light weight CSS library which helps you in developing fast , responsive and powerful interfaces.",
        images: [
          "https://res.cloudinary.com/dfou0tzco/image/upload/v1675620609/MetaUI_jl9rg2.jpg",
        ],
        features: [
          "User can Create / Read / Update / Delete their post.",
          "Authenticated user can update his profile(profile picture, username, email, password).",
          "Client side and server side validation.",
          "Context api for state management.",
          "Search Functionality.",
          "Image Upload with Cloudinary.",
        ],
        tools: ["React", "Javascript", "Nodejs", "MongoDB", "CSS", "SASS"],
        liveLink: "https://meta-ui-app.vercel.app/",
        githubLink: "https://github.com/agasefamircan",
        __v: 0,
        left: false,
      },
      {
        _id: "3",
        title: "Rooms",
        detail:
          "Rooms is a MERN stack Hotel Booking application. Admin Dashboard. SSG & SSR with next.js. State management using Context-api. Search and filter functionality. Client-side & Server-side authentication.",
        images: [
          "https://res.cloudinary.com/dfou0tzco/image/upload/v1675620991/tweet_fagbs6.jpg",
        ],
        features: [
          "Admin Dashboard.",
          "SSG & SSR using Next.js.",
          "Multistep Form.",
          "Context api for state management.",
          "Image Upload with Cloudinary.",
          "Image Slider.",
          "Filter by Min & Max price.",
          "Client-side and Server-side authentication.",
        ],
        tools: [
          "Next.js",
          "React Js",
          "Javascript",
          "Nodejs",
          "MongoDB",
          "SwiperJs",
          "Cloudinary",
          "SASS",
        ],
        liveLink: "https://tweetgenerator.vercel.app/",
        githubLink: "https://github.com/agasefamircan",
        __v: 0,
        left: true,
      },
      {
        _id: "4",
        title: "Admin Dashboard",
        detail:
          "React.js Admin Dashboard.  Content Management User Authorization and management. Security and Permissions. Viewing Data and editing. CRUD functionality or management. Dark & Light Mode. Client-side authentication & Image Upload.",
        images: [
          "https://res.cloudinary.com/drbvugloj/image/upload/v1668216576/new%20folder/dashboard1_m2vqvp.png",
          "https://res.cloudinary.com/drbvugloj/image/upload/v1668216576/new%20folder/dashboard2_ligqjl.png",
          "https://res.cloudinary.com/drbvugloj/image/upload/v1668216576/new%20folder/dashboard3_kvdv1l.png",
          "https://res.cloudinary.com/drbvugloj/image/upload/v1668216578/new%20folder/dashboard4_llxqbz.png",
        ],
        features: [
          "Content Management.",
          "User Authorization and management.",
          "Client-side validation & Image Upload.",
          "Security and Permissions",
          "Viewing Data and editing",
          "CRUD functionality or management.",
          "Dark & Light Mode",
        ],
        tools: [
          "React Js",
          "Javascript",
          "Admin",
          "Nodejs",
          "MongoDB",
          "Cloudinary",
          "MUI",
          "SASS",
        ],
        liveLink: "https://react-admin-dashboard-virid.vercel.app/",
        githubLink: "https://github.com/agasefamircan",
        __v: 0,
        left: false,
      },
      {
        _id: "5",
        title: "E-commerce Shop",
        detail:
          "An e-commerce web application. Users can find chiles on this website and they can order the products through it. I'm using context API for the state management and stripe as an online payment method.",
        images: [
          "https://res.cloudinary.com/drbvugloj/image/upload/v1672551839/samples/ecommerce/Screenshot_from_2023-01-01_11-41-43_uniafd.png",
          "https://res.cloudinary.com/drbvugloj/image/upload/v1672551836/samples/ecommerce/Screenshot_from_2023-01-01_11-41-51_cwpas1.png",
          "https://res.cloudinary.com/drbvugloj/image/upload/v1672551840/samples/ecommerce/Screenshot_from_2023-01-01_11-42-10_quf4ix.png",
          "https://res.cloudinary.com/drbvugloj/image/upload/v1672551836/samples/ecommerce/Screenshot_from_2023-01-01_11-42-17_qdffs5.png",
        ],
        features: [
          "State management using context API",
          "Filter and Search functionality",
          "Stripe for payment method",
        ],
        tools: [
          "Next.JS",
          "Javascript",
          "ReactJS",
          "Nodejs",
          "MongoDB",
          "Cloudinary",
          "MUI",
          "CSS",
        ],
        liveLink: "https://lucianaschiles.vercel.app/",
        githubLink: "https://github.com/agasefamircan",
        left: true,
        __v: 0,
      },
    ],
  };
  const projects = res.message;
  return {
    props: {
      projects: projects,
    },
  };
}
