import Head from "next/head";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import About from "@/components/About/About";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header/Header";
export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio | Agasef</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Header/>
        <About/>
        <Footer/>
      </main>
    </>
  );
}
